Ok, now what if we need to work with a collection of data? In this case we are gonna need other type of data structure, as arrays and vectors. It may look weird, but python has no built-in structure such as an array. Instead of that, it works with lists, that are actually quite more general than arrays. You may wanna take a look on this tutorial: https://www.digitalocean.com/community/tutorials/understanding-lists-in-python-3 


In [13]:
x=[1,2,3,4]
type(x)

list

How to create an empy list:

In [5]:
z=[]
w=list()
print(z,w)

[] []


Adding stuff to the list

In [6]:
z.append(1.) 
print(z)

[1.0]


Adding another thing to the end of the list

In [7]:
z.append(2) 
print(z)

[1.0, 2]


Inserting somethin in the position 1

In [8]:
z.insert(1,'1.5') 
print(z)

[1.0, '1.5', 2]


Add every item inside a list y at the end of a list z

In [11]:
y=[3.,4]
z.extend(y)
print(z)

[1.0, '1.5', 2, 3.0, 4, 3.0, 4]


Lists can contain every other type of variable, including lists!

In [14]:

z.append(x)
print(z)

[1.0, '1.5', 2, 3.0, 4, 3.0, 4, [1, 2, 3, 4]]


In [10]:
type(x)

list

This is how you print an element of a list

In [11]:
print(z[0])

1.0


In [12]:
print(z[5])

IndexError: list index out of range

Getting a piece of a list

In [15]:
a=z[2]
print(a)

3.0


In [14]:
type(a)

float

Slicing the first 6 items of a list

In [16]:
b=z[0:6] 

In [17]:
print(b)

[1.0, '1.5', 3.0, 4, [1, 2, 3, 4]]


There are different ways of removing an item from a list

one can use pop to exclude the last item, and prints what was excluded:

In [18]:
b.pop() 

[1, 2, 3, 4]

In [19]:
print(b)

[1.0, '1.5', 3.0, 4]


one can also use pop to exclude an specific item at, for example, position 1

In [20]:
b.pop(1) 


'1.5'

In [21]:
print(b)

[1.0, 3.0, 4]


If you want a quiet option, you can use del:

In [22]:
del b[1]
print(b)

[1.0, 4]


In [23]:
b.append(3.0)
print(b)

[1.0, 4, 3.0]


With remove, you can exclude the first incidence of a certain value on the list

In [24]:
b.remove(3.0) 
print(b)

[1.0, 4]


Of course, in order to remove something, something must exist ;)

In [25]:
b.remove(5.0)

ValueError: list.remove(x): x not in list

In [26]:
print(z)

[1.0, '1.5', 3.0, 4, [1, 2, 3, 4]]


Differently from strings and tuples, it is possible to change the content of a list

In [27]:
z[1]=5.0
print(z)

[1.0, 5.0, 3.0, 4, [1, 2, 3, 4]]


In [28]:
x[3]='!'
print(x)
print(z)

[1, 2, 3, '!']
[1.0, 5.0, 3.0, 4, [1, 2, 3, '!']]


Finally, as I mentioned this name a couple of times before, there are also structures called tuple. https://www.tutorialspoint.com/python/python_tuples.htm

In [32]:
t=(1,2,3,4)
print(t)

(1, 2, 3, 4)


In [33]:
type(t) 

tuple

They are very similar to list, but they are immutable.

In [29]:
print(t[1:2])

NameError: name 't' is not defined

In [30]:
t[2]=5

NameError: name 't' is not defined

It may be useful to now what is the size of a list

In [15]:
len(z)

8

One way of doing iterations is by using the range function from before

In [16]:
for i in range(len(z)):
    print(z[i])

1.0
1.5
2
3.0
4
3.0
4
[1, 2, 3, 4]


Or you can iterate to each element of a list

In [17]:
for i in z:
    print(i)

1.0
1.5
2
3.0
4
3.0
4
[1, 2, 3, 4]


You can use break to stop a iteration process

In [19]:
x=int(input('type a number between 0 and 10:'))
for i in range(10):
    if x==10:
        break
    else:
        print('I will sum +1')
        print('try number ',str(x))
        x+=1

type a number between 0 and 10:8
I will sum +1
try number  8
I will sum +1
try number  9


Using while to loop

In [45]:
x=int(input('digite um número de 0 a 10:'))
while x<10:
    print('vou somar +1')
    print('tentativa '+str(x))
    x+=1

digite um número de 0 a 10:5
vou somar +1
tentativa 5
vou somar +1
tentativa 6
vou somar +1
tentativa 7
vou somar +1
tentativa 8
vou somar +1
tentativa 9


The most beginner way of writting an ascii file in Python is by doing something like that: (take a look on this tutorial for other ways http://www.pythonforbeginners.com/files/reading-and-writing-files-in-python)

The nomeclature is: w to write, r to read and a to append at the end (without supressing what was written before)

In [46]:
file1=open('nome.txt','w')

In [47]:
pwd

u'/Users/juliaroquette/Dropbox/UFS/2017_2/LabAstro'

In [48]:
file1.write('#just write something')
file1.write('\n')#this goes to a new line
file1.close()

Writing multiple lines and columns

In [49]:
file1=open('nome.txt','a+')
for i in range(10):
    file1.write('nome'+str(i)+'\t') #'\t' do a tab skip
    file1.write(str(i)+'\t')
    if i%2!=0:
        file1.write(str(i*i)+'\n')
    else:
        file1.write(str(0.0)+'\n')    
file1.close()

I chose to show this way of writting files because it is quite similar to what we do in other languages. But I consider it an ugly thing of doing it. So let's reach the powerfull part of Python (the scientific packages), and then we get back to this task of writting and reading files.

Let's talk about Numpy. You can load the package by using. Here is a good reference for numpy routines 
https://docs.scipy.org/doc/numpy/reference/routines.html

In [23]:
import numpy as np

One of the many good things about numpy, is that it knows what an array is. This is good because working with arrays is quicker for several of the things you  may wanna do. Note: it depends on what you wanna do, and you can find an interesting discussion of when is that on stackoverflow: https://stackoverflow.com/questions/176011/python-list-vs-array-when-to-use. A numpy (or scipy) array is just like a vector, which means you can do vector operations on it (multiply by an scalar, transpose, convolve, whatever you list). Here's a good sum up of arrays, for reference: http://pages.physics.cornell.edu/~myers/teaching/ComputationalMethods/python/arrays.html

In [24]:
w=[1,2,3,4,5]
wn=np.array(w)

In [25]:
print(wn,type(wn))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [26]:
t=np.array(w,'str')
print(t,type(t))

['1' '2' '3' '4' '5'] <class 'numpy.ndarray'>


In [28]:
s=np.array(w,'float')
print(s,type(s))

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [34]:
np.nanmax(s)


5.0

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

Some basic operations with arrays

In [35]:
print(s.max(),s.min(),s.mean(),s.std())

5.0 1.0 3.0 1.4142135623730951


Some basic operation with vectors, given the two arrays:

In [39]:
v1=np.array([1./np.sqrt(2),+1./np.sqrt(2)])
v2=np.array([1./np.sqrt(2),-1./np.sqrt(2)])
print(v1)

[0.70710678 0.70710678]


Dot product of the two vectors

In [37]:
np.dot(v1,v2)

0.0

In [40]:
np.dot(v1,v1)

0.9999999999999998

Multiplicating by a scalar

In [42]:
v3=np.array([1.,2.,1.])
x=2.
print(v3*x)

[2. 4. 2.]


Multi-dimensional arrays - Matrix

In [43]:
t1=np.array([[0,1],[10,11]])
print(t1)

[[ 0  1]
 [10 11]]


size of the matrix:

In [44]:
t1.shape

(2, 2)

In [61]:
print(t1[0,0],t1[0,1],t1[1,0],t1[1,1])

0 1 10 11


slicing an array (it is just like with the lists)

In [62]:
t11=t1[0,:]
print(t11,t11.shape)

[0 1] (2,)


Creating an array filled with zeros given an n x m dimension, for example, for 2 x 3:

In [45]:
ze=np.zeros([2,3])
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]]


Creating an array filled with 1 given an n x m dimension, for example, for 3 x 3:

In [46]:
um=np.ones([3,2])
print(um)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Creating an identity matrix with a desired dimension n x n, for example, for n=4

In [47]:
I4=np.identity(4)
print(I4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Applying conditions with numpy.where. In the example: select in the array the elements for which the remainder after division by 3 is different from zero.

In [48]:
a=np.array([32.,23.,66.,88.,34.,33.])
np.where(a%3!=0) 

(array([0, 1, 3, 4]),)

There are three ways of doing this kind of thing with numpy. You can use numpy.where, numpy.argwhere or numpy.nonzero, here is a dicussion on the differences between them https://stackoverflow.com/questions/15976697/difference-between-nonzeroa-wherea-and-argwherea-when-to-use-which

But in the case of numpy.where, it basically transform your condition in a boolean mask

In [71]:
np.where(a%3!=0,1,0) #getting the full boolean mask

array([1, 1, 0, 1, 1, 0])

In [73]:
divisivelpor3=a[np.where(a%3==0)] #Slicing given a condition
print(divisivelpor3)

[66. 33.]
